// AUTO-GENERATED by ffigen - DO NOT EDIT
// Run `dart run ffigen` to regenerate
//
// ignore_for_file: non_constant_identifier_names
// ignore_for_file: unused_field
// ignore_for_file: unused_element
// ignore_for_file: camel_case_types

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint
@ffi.DefaultAsset('package:mecab/src/mecab.dart')
library;

import 'dart:ffi' as ffi;

/// C wrapper of MeCab::Tagger::create(arg)
@ffi.Native<ffi.Pointer<mecab_t> Function(ffi.Pointer<ffi.Char>)>()
external ffi.Pointer<mecab_t> mecab_new2(
  ffi.Pointer<ffi.Char> arg,
);

/// C wrapper of MeCab::Tagger::version()
@ffi.Native<ffi.Pointer<ffi.Char> Function()>()
external ffi.Pointer<ffi.Char> mecab_version();

/// C wrapper of MeCab::getLastError()
@ffi.Native<ffi.Pointer<ffi.Char> Function(ffi.Pointer<mecab_t>)>()
external ffi.Pointer<ffi.Char> mecab_strerror(
  ffi.Pointer<mecab_t> mecab,
);

/// C wrapper of MeCab::deleteTagger(tagger)
@ffi.Native<ffi.Void Function(ffi.Pointer<mecab_t>)>()
external void mecab_destroy(
  ffi.Pointer<mecab_t> mecab,
);

/// C wrapper of MeCab::Tagger::parse(const char *str)
@ffi.Native<
    ffi.Pointer<ffi.Char> Function(
        ffi.Pointer<mecab_t>, ffi.Pointer<ffi.Char>)>()
external ffi.Pointer<ffi.Char> mecab_sparse_tostr(
  ffi.Pointer<mecab_t> mecab,
  ffi.Pointer<ffi.Char> str,
);

/// C wrapper of MeCab::Tagger::parseToNode(const char *str)
@ffi.Native<
    ffi.Pointer<mecab_node_t> Function(
        ffi.Pointer<mecab_t>, ffi.Pointer<ffi.Char>)>()
external ffi.Pointer<mecab_node_t> mecab_sparse_tonode(
  ffi.Pointer<mecab_t> mecab,
  ffi.Pointer<ffi.Char> arg1,
);

/// C wapper of MeCab::Model::create(argc, argv)
@ffi.Native<
    ffi.Pointer<mecab_model_t> Function(
        ffi.Int, ffi.Pointer<ffi.Pointer<ffi.Char>>)>()
external ffi.Pointer<mecab_model_t> mecab_model_new(
  int argc,
  ffi.Pointer<ffi.Pointer<ffi.Char>> argv,
);

/// C wapper of MeCab::Model::create(arg)
@ffi.Native<ffi.Pointer<mecab_model_t> Function(ffi.Pointer<ffi.Char>)>()
external ffi.Pointer<mecab_model_t> mecab_model_new2(
  ffi.Pointer<ffi.Char> arg,
);

/// C wapper of MeCab::deleteModel(model)
@ffi.Native<ffi.Void Function(ffi.Pointer<mecab_model_t>)>()
external void mecab_model_destroy(
  ffi.Pointer<mecab_model_t> model,
);

/// C wapper of MeCab::Model::createTagger()
@ffi.Native<ffi.Pointer<mecab_t> Function(ffi.Pointer<mecab_model_t>)>()
external ffi.Pointer<mecab_t> mecab_model_new_tagger(
  ffi.Pointer<mecab_model_t> model,
);

/// C wapper of MeCab::Model::createLattice()
@ffi.Native<ffi.Pointer<mecab_lattice_t> Function(ffi.Pointer<mecab_model_t>)>()
external ffi.Pointer<mecab_lattice_t> mecab_model_new_lattice(
  ffi.Pointer<mecab_model_t> model,
);

/// DictionaryInfo structure
final class mecab_dictionary_info_t extends ffi.Struct {
  /// filename of dictionary
  /// On Windows, filename is stored in UTF-8 encoding
  external ffi.Pointer<ffi.Char> filename;

  /// character set of the dictionary. e.g., "SHIFT-JIS", "UTF-8"
  external ffi.Pointer<ffi.Char> charset;

  /// How many words are registered in this dictionary.
  @ffi.UnsignedInt()
  external int size;

  /// dictionary type
  /// this value should be MECAB_USR_DIC, MECAB_SYS_DIC, or MECAB_UNK_DIC.
  @ffi.Int()
  external int type;

  /// left attributes size
  @ffi.UnsignedInt()
  external int lsize;

  /// right attributes size
  @ffi.UnsignedInt()
  external int rsize;

  /// version of this dictionary
  @ffi.UnsignedShort()
  external int version;

  /// pointer to the next dictionary info.
  external ffi.Pointer<mecab_dictionary_info_t> next;
}

/// Node structure
final class mecab_node_t extends ffi.Struct {
  /// pointer to the previous node.
  external ffi.Pointer<mecab_node_t> prev;

  /// pointer to the next node.
  external ffi.Pointer<mecab_node_t> next;

  /// pointer to the node which ends at the same position.
  external ffi.Pointer<mecab_node_t> enext;

  /// pointer to the node which starts at the same position.
  external ffi.Pointer<mecab_node_t> bnext;

  /// pointer to the right path.
  /// this value is NULL if MECAB_ONE_BEST mode.
  external ffi.Pointer<mecab_path_t> rpath;

  /// pointer to the right path.
  /// this value is NULL if MECAB_ONE_BEST mode.
  external ffi.Pointer<mecab_path_t> lpath;

  /// surface string.
  /// this value is not 0 terminated.
  /// You can get the length with length/rlength members.
  external ffi.Pointer<ffi.Char> surface;

  /// feature string
  external ffi.Pointer<ffi.Char> feature;

  /// unique node id
  @ffi.UnsignedInt()
  external int id;

  /// length of the surface form.
  @ffi.UnsignedShort()
  external int length;

  /// length of the surface form including white space before the morph.
  @ffi.UnsignedShort()
  external int rlength;

  /// right attribute id
  @ffi.UnsignedShort()
  external int rcAttr;

  /// left attribute id
  @ffi.UnsignedShort()
  external int lcAttr;

  /// unique part of speech id. This value is defined in "pos.def" file.
  @ffi.UnsignedShort()
  external int posid;

  /// character type
  @ffi.UnsignedChar()
  external int char_type;

  /// status of this model.
  /// This value is MECAB_NOR_NODE, MECAB_UNK_NODE, MECAB_BOS_NODE, MECAB_EOS_NODE, or MECAB_EON_NODE.
  @ffi.UnsignedChar()
  external int stat;

  /// set 1 if this node is best node.
  @ffi.UnsignedChar()
  external int isbest;

  /// forward accumulative log summation.
  /// This value is only available when MECAB_MARGINAL_PROB is passed.
  @ffi.Float()
  external double alpha;

  /// backward accumulative log summation.
  /// This value is only available when MECAB_MARGINAL_PROB is passed.
  @ffi.Float()
  external double beta;

  /// marginal probability.
  /// This value is only available when MECAB_MARGINAL_PROB is passed.
  @ffi.Float()
  external double prob;

  /// word cost.
  @ffi.Short()
  external int wcost;

  /// best accumulative cost from bos node to this node.
  @ffi.Long()
  external int cost;
}

/// Path structure
final class mecab_path_t extends ffi.Struct {
  /// pointer to the right node
  external ffi.Pointer<mecab_node_t> rnode;

  /// pointer to the next right path
  external ffi.Pointer<mecab_path_t> rnext;

  /// pointer to the left node
  external ffi.Pointer<mecab_node_t> lnode;

  /// pointer to the next left path
  external ffi.Pointer<mecab_path_t> lnext;

  /// local cost
  @ffi.Int()
  external int cost;

  /// marginal probability
  @ffi.Float()
  external double prob;
}

final class mecab_t extends ffi.Opaque {}

final class mecab_model_t extends ffi.Opaque {}

final class mecab_lattice_t extends ffi.Opaque {}
