// MeCab config.h for Dart Native Assets build.
// Normally generated by autotools. Static version for CBuilder.

#define HAVE_CONFIG_H
#define VERSION "0.996"
#define PACKAGE "mecab"
#define DIC_VERSION 102

// POSIX headers available on macOS/Linux/iOS/Android.
#if !defined(_WIN32)
#define HAVE_FCNTL_H 1
#define HAVE_SYS_STAT_H 1
#define HAVE_SYS_TYPES_H 1
#define HAVE_SYS_MMAN_H 1
#define HAVE_UNISTD_H 1
#define HAVE_DIRENT_H 1
#define HAVE_STRING_H 1
#define HAVE_STDINT_H 1
#define HAVE_PTHREAD_H 1
#define HAVE_MMAP 1
#define HAVE_GETENV 1
#define HAVE_UNSIGNED_LONG_LONG_INT 1
#else
#define HAVE_WINDOWS_H 1
#define HAVE_UNSIGNED_LONG_LONG_INT 1
#define HAVE_GETENV 1
#define HAVE_STRING_H 1
#endif

// No iconv — we handle UTF-8 only.
// No zlib — dictionary compression not used at runtime.

// Default RC file path (overridden at runtime).
#define MECAB_DEFAULT_RC "/usr/local/etc/mecabrc"
